### ISSUE TITLE
如何同时运行两个或多个程序

### ISSUE THREAD

**Issue by capernerl** [ZhelinCheng/bilibili-downloader#110]
您好，我想要同时运行两个脚本，目前在start后会提示Error:listen EADDRINUSE: address already in use : : : 6123
请问应该在哪里做出修改呢？

**Comment by ZhelinCheng** [comment]
更改环境变量的BLI_PORT，一个用6123，一个用6124

**Comment by capernerl** [comment]
> 更改环境变量的BLI_PORT，一个用6123，一个用6124

请问环境变量的修改是在哪个文件？ 不太专业，不好意思

**Comment by capernerl** [comment]
> 更改环境变量的BLI_PORT，一个用6123，一个用6124

已找到，多谢。dist>main.js
