### ISSUE TITLE
关于”视频长度超过 600 秒，跳过下载“的问题

### ISSUE THREAD

**Issue by SuLingGG** [ZhelinCheng/bilibili-downloader#97]
开发者你好~
这是一个对我非常有用的项目！

但在使用过程中，我发现一些视频无法被正常下载。查看日志时发现这样一条警告：

```
视频长度超过600秒，跳过下载
```

之后我手动复制日志中的视频链接粘贴到 IDM，视频可以正常下载和播放。
使用 IDM 下载到本地的视频也是完整的，视频时长也大于 600 秒。

请问设计这个 600 秒限制是出于什么目的或者为了规避哪些问题呢~ 如果影响不大是否可以取消这个限制呢？

**Comment by ZhelinCheng** [comment]
这个不是问题，我今天加个环境变量，你晚上更新一下即可

**Comment by SuLingGG** [comment]
> 这个不是问题，我今天加个环境变量，你晚上更新一下即可

多谢~

**Comment by ZhelinCheng** [comment]
好了，更新一下，不需要改任何配置。
